# Generated by Django 6.0 on 2025-12-25 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='qualification',
        ),
    ]
